---
version: 2
sources:
- name: "andre_dev.alteryx_spatial"
  database: "andre_dev"
  schema: "alteryx_spatial"
  tables:
  - name: "new_england"
    columns:
    - name: "name"
      dataType:
        type: "String"
    - name: "geometry"
      dataType:
        type: "String"
    type: "table"
  - name: "poly_build_02"
    columns:
    - name: "route_id"
      dataType:
        type: "String"
    - name: "stop_schedule"
      dataType:
        type: "Timestamp"
    - name: "latitude"
      dataType:
        type: "Double"
    - name: "longitude"
      dataType:
        type: "Double"
    type: "table"
