---
version: 2
sources:
- name: "andre_dev.alteryx_spatial"
  database: "andre_dev"
  schema: "alteryx_spatial"
  tables:
  - name: "new_england"
    columns:
    - name: "name"
      dataType:
        type: "String"
    - name: "geometry"
      dataType:
        type: "String"
    type: "table"
  - name: "poly_build_02"
    columns:
    - name: "route_id"
      dataType:
        type: "String"
    - name: "stop_schedule"
      dataType:
        type: "Timestamp"
    - name: "latitude"
      dataType:
        type: "Double"
    - name: "longitude"
      dataType:
        type: "Double"
    type: "table"
  - name: "airport_fn_01"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "state"
      dataType:
        type: "String"
    - name: "name"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    type: "table"
  - name: "us_airports_2"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "state"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    - name: "iata_code"
      dataType:
        type: "String"
    - name: "name"
      dataType:
        type: "String"
    type: "table"
  - name: "us_cities"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "state"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    - name: "population"
      dataType:
        type: "Integer"
    type: "table"
  - name: "us_cities_50k"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "state"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    - name: "population"
      dataType:
        type: "Integer"
    type: "table"
  - name: "us_cities_100k"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "state"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    - name: "population"
      dataType:
        type: "Integer"
    type: "table"
  - name: "us_airports_50k"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "state"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    - name: "iata_code"
      dataType:
        type: "String"
    - name: "name"
      dataType:
        type: "String"
    type: "table"
  - name: "distribution_centers"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "name"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    type: "table"
- name: "andre_dev.data"
  database: "andre_dev"
  schema: "data"
  tables:
  - name: "nam_cities"
    columns:
    - name: "city"
      dataType:
        type: "String"
    - name: "country"
      dataType:
        type: "String"
    - name: "lat"
      dataType:
        type: "Double"
    - name: "lon"
      dataType:
        type: "Double"
    - name: "population"
      dataType:
        type: "Double"
    type: "table"
