---
version: 2
models:
- name: "SpatialInfo_04__calc_line_geometry_info"
  tags:
  - "prophecy_temp"
- name: "SpatialInfo_04__calc_spatial_metrics"
  tags:
  - "prophecy_temp"
- name: "SpatialInfo_04__calc_us_state_centroids"
  tags:
  - "prophecy_temp"
