---
version: 2
models:
- name: "PolyBuild__Line"
  tags:
  - "prophecy_temp"
- name: "PolyBuild__PolyBuild_1_1"
  tags:
  - "prophecy_temp"
- name: "PolyBuild__Polygon"
  tags:
  - "prophecy_temp"
- name: "PolyBuild__build_route_polygon"
  tags:
  - "prophecy_temp"
